"""Initial schema

Revision ID: 471775a0812b
Revises: 
Create Date: 2026-02-01 00:16:44.919174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '471775a0812b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    insp = inspect(bind)
    tables = set(insp.get_table_names())

    if 'visitor' not in tables:
        op.create_table(
            'visitor',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('ip_address', sa.String(length=50), nullable=True),
            sa.Column('city', sa.String(length=100), nullable=True),
            sa.Column('state', sa.String(length=100), nullable=True),
            sa.Column('visited_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    if 'user' not in tables:
        op.create_table(
            'user',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('phone', sa.String(length=20), nullable=True),
            sa.Column('email', sa.String(length=150), nullable=False, unique=True),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column('role', sa.String(length=20), nullable=False, server_default='user'),
            sa.Column('created_at', sa.DateTime(), nullable=True),
        )
    else:
        existing_cols = {c['name'] for c in insp.get_columns('user')}
        if 'phone' not in existing_cols:
            with op.batch_alter_table('user', schema=None) as batch_op:
                batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = inspect(bind)
    tables = set(insp.get_table_names())

    if 'user' in tables:
        existing_cols = {c['name'] for c in insp.get_columns('user')}
        if 'phone' in existing_cols:
            with op.batch_alter_table('user', schema=None) as batch_op:
                batch_op.drop_column('phone')

    if 'visitor' in tables:
        op.drop_table('visitor')
    # ### end Alembic commands ###
